### ISSUE TITLE
Example for adding to a Gridadapter 

### ISSUE THREAD

**Issue by axsddlr** [shalskar/PeekAndPopDemo#2]
I want to implement this to a grid view, I have a gridadapter that pulls images from json. Having trouble adding this implement so I can long press each item in grid to use peek and pop feature..

**Comment by shalskar** [comment]
The demo app uses a RecyclerView with a GridlayoutManager (this is the preferred pattern for showing items in a scrollable grid.) so you could use it as a reference.

However if you need to use a GridView, I believe you could use the view in the getView() method of the adapter supplied to the GridView, as well as the position.

**Comment by harshvardhan** [comment]
When I do this with a Fragment, the peek view doesn't goes away upon removal of touch. It stays there and even on back press it cements itself there while things are happening as they should happen on back press.

Is this possible with a fragment?
