### ISSUE TITLE
Peek View cements itself to Activity

### ISSUE THREAD

**Issue by harshvardhan** [shalskar/PeekAndPopDemo#3]
When I do this with a Fragment, the peek view doesn't goes away upon removal of touch. It stays there and even on back press it cements itself there while things are happening as they should happen on back press.

**Comment by harshvardhan** [comment]
The pop function in the **PeekAndPop.java** never gets called. Which in turn calls `onGeneralActionListener.onPop(longClickView, index)`.

**Comment by shalskar** [comment]
Do you have your project here on Github? I could pull it down and see if I can find the root to the issue. I have used this library inside of Fragments before and haven't experienced such a problem.

**Comment by harshvardhan** [comment]
I wouldn't be able to share the whole project, for NDA reasons. Let me give you snippets. 

activity_main.xml -> the FrameLayout with container id is the one where fragments are shown.
WishlistFragment.java -> is the one where I have the recyclerview where peekandpop is intended to work.
fragment_wishlist.xml -> this layout contains the recyclerview for peekandpop.
WishlistInstituteListAdapter.java -> Adapter for the aforementioned recyclerview.
card_wishlist_institute_list_grid_view.xml -> counterpart of demo_object. 
peek_view.xml -> layout for peek view.
[snippets.zip](https://github.com/shalskar/PeekAndPopDemo/files/292838/snippets.zip)

**Comment by harshvardhan** [comment]
I used a fragment in the peekAndPopDemo and it worked. Its something with my layout or code which is not letting peek_view stay in focus to receive touch up event. I was suspecting that if we add the peek view to the fragment instead of activity, it should do. I am going to try that next.
But let me know if you have any idea about this. You can close this if you haven't.

**Comment by shalskar** [comment]
Yeah that sounds like it could be the problem. Looking through your code I couldn't see anything obvious that would that would would remove focus from the peek view. I hope you are able to find a solution!

**Comment by harshvardhan** [comment]
For touch up event to reach the relevant view I had to add this to RecyclerView's child's layout, in demo it would be demo_object.xml root layout:

```
    android:clickable="true"
    android:focusableInTouchMode="true"
    android:focusable="true"
```

Thanks for the help Vincent Te Tau.

**Comment by shalskar** [comment]
Cool, glad you worked it out, I will keep this in mind if anyone else has a similar problem!
